### ISSUE TITLE
 Logo + Claim Teilnehmer-Emails Veranstaltungen

### ISSUE THREAD

**Issue by barbara-kids-team** [gollenia/events#5]
Ist es möglich, bei den Antwort-E-Mails bei den Veranstaltungen unser kids-team Logo mit einzufügen?
So, wie bei den E-Mails über Outlook?
Also:
dein kids-team

**Logo + Claim**

Möslstr. 13
5112 Lamprechtshausen
Österreich

Tel.: +43 (0) 660-7933540
info@kids-team.at
www.kids-team.at
Gratis Downloadbereich: https://downloads.kids-team.at/

**Comment by gollenia** [comment]
Mit dem derzeitigen System nicht, eventuell später Mal über Brevo
